export const itemsData = [
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
  {
    productName: "Apple Macbook Pro",
    imgSrc: "assets/img/headphone.jpg",
    mrp: 599,
    offerPrice: 499,
    ratingImg: "assets/img/stars.JPG",
  },
];
